export const SET_COLLECTIONS =  'global/SET_COLLECTIONS';
export const SET_COLLECTIONS_SUCCESS = 'global/SET_COLLECTIONS_SUCCESS';
export const SET_COLLECTIONS_ERROR = 'global/SET_COLLECTIONS_ERROR';
