export const SET_COLLECTIONS =  'global/SET_COLLECTIONS';
export const SET_COLLECTIONS_SUCCESS = 'global/SET_COLLECTIONS_SUCCESS';
export const SET_COLLECTIONS_ERROR = 'global/SET_COLLECTIONS_ERROR';

export const SET_COLLECTION_PRODUCTS =  'global/SET_COLLECTION_PRODUCTS';
export const SET_COLLECTION_PRODUCTS_SUCCESS = 'global/SET_COLLECTION_PRODUCTS_SUCCESS';
export const SET_COLLECTION_PRODUCTS_ERROR = 'global/SET_COLLECTION_PRODUCTS_ERROR';

export const SET_PRODUCTS_NEXT_PAGE =  'global/SET_PRODUCTS_NEXT_PAGE';
export const SET_PRODUCTS_NEXT_PAGE_SUCCESS = 'global/SET_PRODUCTS_NEXT_PAGE_SUCCESS';
